<?php
/**
 * Created by PhpStorm.
 * User: 29393
 * Date: 2018/7/3
 * Time: 16:18
 */
namespace app\model;
use core\lib\model;

class sign extends model {

    public function sel($table,$columns = "*",$where = false){
        if($where){
            return $this->select($table,$columns,$where);
        }else{
            $res = $this->select($table,$columns);
            return $res;
        }
    }

    public function add($table, $datas)
    {
        parent::insert($table, $datas); // TODO: Change the autogenerated stub
        return parent::id();
    }

    public function edit($table, $data, $where = null)
    {
        return parent::update($table, $data, $where)->rowCount(); // TODO: Change the autogenerated stub
    }

    public function del($table, $where)
    {
        return parent::delete($table, $where)->rowCount(); // TODO: Change the autogenerated stub
    }
}